# Generated by Django 4.2.7 on 2023-11-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LatestStatus', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('LatestStatusAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus2',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order2')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
